

spring:
  profiles:
    active: "prod"

  datasource:
    url: jdbc:mysql://localhost:3306/accountdb
    username: root
    password: root
  application:
    name: "account"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: "*"



