spring:
  config:
    activate:
      on-profile: "qa"

cards:
  message: "Hi there from cards from qa"
  contactDetails:
    name: "Santhosh"
    email: "santhosh@gmail.com"
  onCallSupport:
    - (91)9988998899
    - (91)8899889988

build:
  version: "3.0"