spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "2.0"

loans:
  message: "Hi there from loans from prod"
  contactDetails:
    name: "Santhosh"
    email: "santhosh@gmail.com"
  onCallSupport:
    - (91)9988998899
    - (91)8899889988