




build:
  version: "1.0"

cards:
  message: "Hi there from cards"
  contactDetails:
    name: "Santhosh"
    email: "santhosh@gmail.com"
  onCallSupport:
    - (91)9988998899
    - (91)8899889988

