spring:
  application:
    name: "configServer"

  profiles:
    #active: native
    active: git

  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
        git:
          uri: "https://github.com/devHub24/eazyBankConfig.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "ZRZ6vZ8eVAc9mKEVhcWzLfkUNCzkHMwH"


server:
  port: 8071
